# Generated by Django 5.0.3 on 2024-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_time_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sleepiness_level', models.IntegerField()),
            ],
        ),
    ]
